<?php

namespace App\Services;

use Illuminate\Support\Facades\Cache;
use Carbon\Carbon;

class ChangelogService
{
    private const CACHE_TTL    = 21600;
    private const COMMITS_KEY  = 'changelog:commits';
    private const AUTHORED_KEY = 'changelog:authored';

    private const CATEGORY_MAP = [
        'feature'     => ['label' => 'Feature',     'color' => '#22c55e', 'bg' => '34,197,94'],
        'improvement' => ['label' => 'Improvement', 'color' => '#6366f1', 'bg' => '99,102,241'],
        'bugfix'      => ['label' => 'Bug Fix',     'color' => '#ef4444', 'bg' => '239,68,68'],
        'design'      => ['label' => 'Design',      'color' => '#a855f7', 'bg' => '168,85,247'],
        'performance' => ['label' => 'Performance', 'color' => '#f59e0b', 'bg' => '245,158,11'],
        'security'    => ['label' => 'Security',    'color' => '#f97316', 'bg' => '249,115,22'],
        'general'     => ['label' => 'Update',      'color' => '#71717a', 'bg' => '113,113,122'],
    ];

    private const AUTHORED_CATEGORY_MAP = [
        'feature'     => ['label' => 'Feature',     'color' => '#22c55e', 'bg' => '34,197,94'],
        'improvement' => ['label' => 'Improvement', 'color' => '#6366f1', 'bg' => '99,102,241'],
        'bug'         => ['label' => 'Bug Fix',     'color' => '#ef4444', 'bg' => '239,68,68'],
        'design'      => ['label' => 'Design',      'color' => '#a855f7', 'bg' => '168,85,247'],
        'licensing'   => ['label' => 'Licensing',   'color' => '#f59e0b', 'bg' => '245,158,11'],
        'general'     => ['label' => 'Update',      'color' => '#71717a', 'bg' => '113,113,122'],
    ];

    private const AUTHORED_TYPE_MAP = [
        'warning' => ['label' => 'Warning', 'color' => '#f97316', 'bg' => '249,115,22'],
        'info'    => ['label' => 'Info',    'color' => '#3b82f6', 'bg' => '59,130,246'],
        'update'  => null,
    ];

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    public function commits(): array
    {
        return Cache::remember(self::COMMITS_KEY, self::CACHE_TTL, fn () => $this->fetchAndParseCommits());
    }

    public function authored(): array
    {
        return Cache::remember(self::AUTHORED_KEY, self::CACHE_TTL, fn () => $this->fetchAuthoredEntries());
    }

    public function availableMonths(string $source = 'commits'): array
    {
        $entries = match($source) {
            'authored' => $this->authored(),
            'all'      => array_merge($this->commits(), $this->authored()),
            default    => $this->commits(),
        };
    
        return collect($entries)
            ->groupBy(fn ($e) => $e['year'] . '-' . str_pad($e['month'], 2, '0', STR_PAD_LEFT))
            ->keys()
            ->sort()
            ->reverse()
            ->values()
            ->all();
    }

    public function categories(): array
    {
        return self::CATEGORY_MAP;
    }

    public function flush(): void
    {
        Cache::forget(self::COMMITS_KEY);
        Cache::forget(self::AUTHORED_KEY);
    }

    // -----------------------------------------------------------------------
    // Commits — read from static JSON file generated by generate-changelog.php
    // -----------------------------------------------------------------------

    private function fetchAndParseCommits(): array
    {
        $path = storage_path('app/changelog.json');
    
        if (! file_exists($path)) {
            return [];
        }
    
        $data = json_decode(file_get_contents($path), true);
    
        if (! is_array($data)) {
            return [];
        }
    
        $tenantNames = [
            'vortex', 'jolly', 'jollyvip', 'phatlads', 'ritas', 'winthisnow', 'karma',
            'autocomps', 'marras', 'luckyducky', 'lightning', 'winnerwinner', 'maxxx',
            'enchantedlives', 'lustraffles', 'obrienslaravel', 'demo', 'ritasriches',
            'westcoast', 'missmoneypenny', 'auwins', 'sunnysgiveaways', 'itsyourluckyday',
            'wrights', 'cairn', 'vincere', 'mpcomps', 'madmac', 'stashed', 'podium',
            'prizeparty', 'crazycat', 'collectorsvault', 'phantomgiveaways', 'topbanana',
            'deluxecomps', 's2a', 'luxsywins', 'smashdrop',
        ];
    
        return collect($data)
            ->filter(function ($entry) use ($tenantNames) {
                $haystack = strtolower(($entry['title'] ?? '') . ' ' . ($entry['body'] ?? ''));
                foreach ($tenantNames as $tenant) {
                    if (str_contains($haystack, $tenant)) {
                        return false;
                    }
                }
                return true;
            })
            ->values()
            ->all();
    }

    // -----------------------------------------------------------------------
    // Authored entries — live from TenantMessage, target=all only
    // -----------------------------------------------------------------------

    private function fetchAuthoredEntries(): array
    {
        return [];
    }

    private function normaliseAuthoredEntry(\App\Models\TenantMessage $m): array
    {
        $typeEntry = self::AUTHORED_TYPE_MAP[$m->type] ?? null;

        if ($typeEntry !== null) {
            $meta = $typeEntry;
        } else {
            $meta = self::AUTHORED_CATEGORY_MAP[$m->category] ?? self::AUTHORED_CATEGORY_MAP['general'];
        }

        if ($m->type === 'warning') {
            $meta['label'] = match($m->severity) {
                'critical' => 'Critical Warning',
                'medium'   => 'Warning',
                default    => 'Notice',
            };
            $meta['color'] = match($m->severity) {
                'critical' => '#ef4444',
                'medium'   => '#f97316',
                default    => '#eab308',
            };
            $meta['bg'] = match($m->severity) {
                'critical' => '239,68,68',
                'medium'   => '249,115,22',
                default    => '234,179,8',
            };
        }

        $date = Carbon::parse($m->published_at);

        return [
            'id'         => $m->id,
            'source'     => 'authored',
            'title'      => $m->title,
            'body'       => $m->body,
            'type'       => $m->type,
            'severity'   => $m->severity,
            'category'   => $m->category,
            'resolved'   => (bool) $m->is_paid,
            'date'       => $date->toDateString(),
            'date_label' => $date->format('j M Y'),
            'year'       => (int) $date->format('Y'),
            'month'      => (int) $date->format('n'),
            'timestamp'  => $date->timestamp,
            'meta'       => $meta,
        ];
    }
}